### PR TITLE
lowercase security schemes

### PR DESCRIPTION
**Pull request by XVincentX**
1. Security Scheme are case insensitive, so we can normalise them
2. Use a WAY better `DeepPartial` definition that does not lose typings

### CODE REVIEW

**Comment by marbemac** [comment]
Does it make sense to replace the `DeepPartial` in stoplight types with this one so that we use it throughout ecosystem?

**Comment by XVincentX** [comment]
@marbemac 

Yes, the one that @stoplight/types is offering is broken and it gets easily into a bunch of `unknown/never` fields that makes the types incorrect and impossible to use

**Comment by marbemac** [comment]
@XVincentX could you put in a PR to types that either copies the deep partial over from that other package, or re-exports it (assuming other package doesn't have too much other crap we don't need, or is only types in which case doesn't matter)?

I'll approve that and then can update this PR to use the updated deep partial, then merge.

That work?

**Comment by XVincentX** [comment]
@marbemac https://github.com/stoplightio/types/pull/67

**Comment by marbemac** [comment]
make sure to put correct merge message!

**Pull request merged**
