### PR TITLE
fix: correctly set csv type to comma delimited

### PR DESCRIPTION
**Pull request by XVincentX**

### CODE REVIEW

**Comment by philsturgeon** [comment]
Got some unit tests? :)

**Comment by XVincentX** [comment]
No, but I do not mind writing some.

**Comment by XVincentX** [comment]
@philsturgeon Although they were using snapshot, there were effectively unit tests. I've modified them to not use snapshots anymore and assert the property presence and value directly. I do not believe there's anything else we can do here.

**Comment by lag-of-death** [comment]
looks good :+1: let's add some description though ;)

**Pull request merged**
